# Generated by Django 3.0.8 on 2020-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=225, unique=True, verbose_name='Title of category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(help_text='400x400 px required', upload_to='category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='title of the Listing item', max_length=225),
        ),
    ]
