# Generated by Django 3.0.8 on 2020-10-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201002_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='current price of Listing during auction', max_digits=9),
        ),
    ]
