# Generated by Django 3.0.8 on 2020-10-02 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
