# Generated by Django 3.1.2 on 2020-10-04 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201003_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
