# Generated by Django 3.1.2 on 2020-10-04 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201004_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winners',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='winners',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
